name : Deploy to Railway

on: 
  push: 
      branches: [main]


jobs: 
  helloworld: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Imprimir en consola 
      run:
        echo "Hello World, GITHUB ACTIONS"

  test:
    needs: helloworld
    runs-on: ubuntu-latest      

    steps: 
    - uses: actions/checkout@v4

    - name: Set up python 3.13
      uses: action/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install libraries 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt   

    - name: Test FastApi imports 
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGODB_URI: ${{ secrets.MONGO_URI }}   # por si tu código usa este
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        python -c "from main import app; print('FASTAPI app imported succes')"

